spring.application.name=auth-service

server.port = 8082
app.auth.tokenSecret=eae68a6cf5b767358b3cf4318b2fbe97576f8c8a0b27793b0bae4d8abb3cf009
app.auth.tokenExpiration=120000
app.auth.refreshTokenExpiration=864000000

eureka.client.enabled=false